DROP TABLE IF EXISTS [USER];
CREATE TABLE [USER] 
    (UID INT,
     NAME CHAR(10) NOT NULL,
     SEX CHAR(2),
     BYEAR INT,
     CITY CHAR(10),
     PRIMARY KEY (UID)
    );

DROP TABLE IF EXISTS LABEL;
CREATE TABLE LABEL
    (LID INT,
     LNAME CHAR(10) NOT NULL,
     PRIMARY KEY (LID)
    );

DROP TABLE IF EXISTS MBLOG;
CREATE TABLE MBLOG
    (BID INT,
     TITLE CHAR(20) NOT NULL,
     UID INT,
     PYEAR INT,
     PMONTH INT,
     PDAY INT,
     CONT CHAR(255),
     PRIMARY KEY (BID),
     FOREIGN KEY (UID) REFERENCES [USER].UID
    );

DROP TABLE IF EXISTS B_L;
CREATE TABLE B_L
    (BID INT,
     LID INT,
     PRIMARY KEY (BID,LID),
     FOREIGN KEY (BID) REFERENCES MBLOG.BID,
     FOREIGN KEY (LID) REFERENCES LABLE.LID
    );

DROP TABLE IF EXISTS FOLLOW;
CREATE TABLE FOLLOW
    (UID INT,
     UIFFLED INT,
     PRIMARY KEY (UID,UIFFLED),
     FOREIGN KEY (UID) REFERENCES [USER].UID,
     FOREIGN KEY (UIFFLED) REFERENCES [USER].UID
    );

DROP TABLE IF EXISTS FRIENDS;
CREATE TABLE FRIENDS
    (UID INT,
     FUID INT,
     PRIMARY KEY (UID,FUID),
     FOREIGN KEY (UID) REFERENCES [USER].UID,
     FOREIGN KEY (FUID) REFERENCES [USER].UID
    );

DROP TABLE IF EXISTS SUB;
CREATE TABLE SUB
    (UID INT,
     LID INT,
     PRIMARY KEY (UID,LID),
     FOREIGN KEY (UID) REFERENCES [USER].UID,
     FOREIGN KEY (LID) REFERENCES LABEL.LID
    );

DROP TABLE IF EXISTS THUMB;
CREATE TABLE THUMB
    (UID INT,
     BID INT,
     PRIMARY KEY (UID, BID),
     FOREIGN KEY (UID) REFERENCES [USER].UID,
     FOREIGN KEY (BID) REFERENCES MBLOG.BID
    );

DROP TABLE IF EXISTS TOPDAY;
CREATE TABLE TOPDAY
    (TYEAR INT,
     TMONTH INT,
     TDAY INT,
     BID INT,
     TNO INT,
     PRIMARY KEY (TYEAR,TMONTH,TDAY,BID),
     FOREIGN KEY (BID) REFERENCES MBLOG.BID
    );

